---
- name: Docker Image Build
  hosts: docker
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/ec2-user/docfiles
    - name: Copy WAR file
      copy:
       src: target
       dest: /home/ec2-user/docsfiles
    - name : Build image
      command: docker build -t madandevops2024/shoppingsite222 .
    - name : Push Docker Image
      command: docker push madandevops2024/shoppingsite222
