---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-site-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: shopping-site-pod
      labels:
        app: shopping-app
        env: dev
        color: blue
    spec:
      containers:
        - name: shopping-app-container
          image: madandevops2024/shoppingsite222
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-site-nodeport-svc
spec:
  type: LoadBalancer
  selector:
    color: blue #Pod label which we have created under labels
  ports:
    - port: 80
      targetPort: 8080
...

