---
- name: Docker Image Build
  hosts: docker
  become: yes
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/ansadmin
    - name: Copy WAR file
      copy:
       src: target
       dest: /home/ansadmin
    - name : Build image
      command: docker build -t madandevops2024/flipkartsite21 .
    - name : Push Docker Image
      command: docker push madandevops2024/flipkartsite21
- name: Deployment into Kubernetes Cluster
  hosts: eks
  tasks:
   - name: 
     copy:
       src: DeploymentIntoK8sCluster.yml
       dest: /home/ansadmin
   - name: 
     copy:
       src: LB-Service.yml
       dest: /home/ansadmin
   - name : K8S Deployment
     command: kubectl apply -f DeploymentIntoK8sCluster.yml
   - name : LB Service
     command: kubectl apply -f LB-Service.yml
